# Ease of Use
alias sl="ls"
alias l="ls"
alias ll="ls -la"
alias reload="exec $SHELL -l"
alias rl="exec $SHELL -l"

# Shortcuts
alias dt="cd ~/Desktop"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias ws="cd ~/workspace"
