set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

"""""""""""""""""""
" NERDTREE TWEAKS "
"""""""""""""""""""

" Ctrl + n to toggle nerdtree
map <C-n> :NERDTreeToggle<CR>

" Nerdtree appears on left
let g:NERDTreeWinPos = "left"

" Open nerdtree on vim start on a file
" autocmd vimenter * NERDTree

" Open nerdtree on vim start no files specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Open nerdtree on vim start on a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

" Close vim if the only window left is nerdtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Set default arrows
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" disable arrow keys
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>

set number
set number
set tabstop=4

inoremap jj <ESC>

"Copy/Paste to PRIMARY (copy-on-select)
vnoremap <Leader>y "*y
vnoremap <Leader>p "*p

"Copy/Paste to CLIPBOARD (^C, ^V)
vnoremap <Leader>Y "+y
vnoremap <Leader>P "+p
